version: '3.8'

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - openwebui-prod-data:/app/backend/data
    restart: always

volumes:
  openwebui-prod-data:
